# Generated by Django 4.1 on 2024-01-20 23:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="почта"),
                ),
                ("fullname", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="тема письма")),
                ("body", ckeditor.fields.RichTextField(verbose_name="тело письма")),
            ],
            options={
                "verbose_name": "Сообщение для рассылки",
                "verbose_name_plural": "Сообщения рассылок",
            },
        ),
        migrations.CreateModel(
            name="MailLogger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время последней попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=150, verbose_name="статус попытки"),
                ),
                (
                    "mail_backend_response",
                    models.CharField(max_length=150, verbose_name="ответ почтового сервера"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_loggers",
                        to="mailing.mailmessage",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог рассылки",
                "verbose_name_plural": "Логи рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="время рассылки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "раз в день"),
                            (7, "раз в неделю"),
                            (30, "раз в месяц"),
                        ],
                        default=30,
                        verbose_name="периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "завершена"),
                            ("created", "создана"),
                            ("launched", "запущена"),
                        ],
                        default="created",
                        editable=False,
                        max_length=150,
                        verbose_name="статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="mailings",
                        related_query_name="mailing",
                        to="mailing.client",
                        verbose_name="клиенты",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(
                        related_name="mailings",
                        related_query_name="mailing",
                        to="mailing.mailmessage",
                        verbose_name="сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылки",
            },
        ),
    ]
