# Generated by Django 4.1 on 2024-01-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "завершена"),
                    ("created", "создана"),
                    ("launched", "запущена"),
                ],
                default="created",
                max_length=150,
                verbose_name="статус",
            ),
        ),
    ]
