# Generated by Django 4.1 on 2024-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_client_owner_mailingsettings_owner_mailmessage_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="is_active",
            field=models.BooleanField(default=True, editable=False, verbose_name="активна"),
        ),
    ]
