# Generated by Django 4.1 on 2024-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_mailingsettings_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingsettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активна"),
        ),
    ]
