# Generated by Django 4.1 on 2024-01-29 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0005_alter_mailingsettings_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingsettings",
            options={
                "ordering": ("-pk",),
                "verbose_name": "Настройка рассылки",
                "verbose_name_plural": "Настройки рассылки",
            },
        ),
    ]
